---
title: CV
excerpt: My current CV
date: 2025-01-25
published-title: CV last updated
engine: knitr 
cv:
  pdf: "/_assets/documents/CV.pdf"
---

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    Download a PDF
  </a>
</p>
```  

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>

## Education  
- Ph.D in Statistics, Stellenbosch University; South Africa, USA 2022
- Msc. in Mathematical Sciences, African Institute for Mathematical Sciences; Ghana, 2014
- Msc. in Financial Management,  Amity University, India, 2012
- Bsc. in Applied Mathematics, University of Douala; Cameroon, 2009


## Work experience  


  
## Skills

* Language
  - French: Native
  - English: Fluent 
* Computer Literacy
  * Programming Languages: Python, R
  * Software Development Tools: Git, GitHub


## Publications

- <a href="/publication/pub3/index.qmd" target="_blank" style="text-decoration:none">Generalized EXTRA stochastic gradient Langevin dynamics</a>  


  
## Talks and Presentations  

- <a href="/talks/2023-11-20-candi.qmd" style="text-decoration:none"> The Heavy-Tail Phenomenon in Decentralized Stochastic Gradient Descent</a>  
  November 20, 2023  

  
## Teaching

  - <a href="/teaching/sp25.qmd" style="text-decoration:none"> Spring 2025: MAC2311 Calculus and Analytic Geometry I</a> 
 
## Awards and Affiliations
### Awards  


### Affiliations  
- [Bangladesh Mathematical Society: Life Member](https://www.bdmathsociety.org/){target="_blank" style="text-decoration:none"}
