---
listing: 
  - id: ds-projects
    contents: "/portfolio/dsp"
    type: grid
    sort: "date desc"
    date-format: full
    fields: [image, date, title]
    sort-ui: [title, date]
    feed: true
  - id: spd-projects
    contents: "/portfolio/spd"
    type: grid
    sort: "date desc"
    date-format: full
    fields: [image, date, title]
    sort-ui: [title, date]
    feed: true
  - id: tcng
    contents: teaching
    type: table
    fields: [title]
    sort: "date desc"
    feed: true
---   

## Data Science and Machine Learning Projects  


::: {#ds-projects}  
:::  

## Software Development  

::: {#spd-projects}  
:::  

## My services 
I give back to my community through mentorship because I am passionate about supporting others. I believe that everyone has the potential to succeed, and I want to help them realize their goals.  I enjoy sharing my knowledge and experiences to inspire and empower others to reach their full potential. I  offer advice, support, encouragement, and guidance to help you develop.

If you're an undergraduate, graduate or PhD candidate,  I'm here to help you navigate this exciting yet challenging phase.  Whether you need help with academics, networking opportunities, or simply need someone to listen, I am dedicated to being a resource for you. I understand the struggles and obstacles that can arise during these stages of education, and I am committed to helping you overcome them. Together, we can work towards your goals. Feel free to reach out and benefit from the support  I can offer. Your success is important to me. 
::: {#tcng}
:::  






<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>

